package org.example.marketdata;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/** Reads and writes candles in the {@code candles} database table. */
@Repository
public class CandleRepository {

    private final JdbcTemplate jdbcTemplate;

    public CandleRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /** Returns the number of stored candles. */
    public Integer count() {
        return jdbcTemplate.queryForObject("SELECT COUNT(*) FROM candles", Integer.class);
    }

    /** Returns all candles, ordered by open time (oldest first). */
    public List<Candle> findAll() {
        return jdbcTemplate.query(
                "SELECT id, symbol, open_time, open, high, low, close, volume FROM candles ORDER BY open_time",
                (rs, rowNum) -> new Candle(
                        rs.getLong("id"),
                        rs.getString("symbol"),
                        LocalDateTime.parse(rs.getString("open_time")),
                        BigDecimal.valueOf(rs.getDouble("open")),
                        BigDecimal.valueOf(rs.getDouble("high")),
                        BigDecimal.valueOf(rs.getDouble("low")),
                        BigDecimal.valueOf(rs.getDouble("close")),
                        rs.getLong("volume")
                )
        );
    }

    /** Inserts a candle; its {@code id} is ignored and generated by the database. */
    public void save(Candle candle) {
        jdbcTemplate.update(
                "INSERT INTO candles (symbol, open_time, open, high, low, close, volume) VALUES (?, ?, ?, ?, ?, ?, ?)",
                candle.symbol(),
                candle.openTime().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
                candle.open(),
                candle.high(),
                candle.low(),
                candle.close(),
                candle.volume()
        );
    }
}
